### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by davidswelt** [Klizzy/ice-highspeed#1]
Tried this several times: it does not work.
en0 seems to be indeed my Wifi interface, and the MAC address is being changed, although a different one is what shows up in Sys Prefs -> Network -> Advanced -> Hardware.  (This shows one that is similar, apart from the first two hex digits, to what ifconfig shows for p2p0.)
WifiOnICE does not perform a reset, even if the network connection is renewed and the DHCP name is changed.  I'm not sure if the MAC address is changed effectively for the Wifi network.  
Maybe a MacOS Mojave issue?
This used to work (when I tried more than a year ago, with an older OS).

**Comment by Klizzy** [comment]
The old address will still be displayed in the preferences.
You can verify it it really has changed with the following command:
```ifconfig en0 |grep ether | cut -c 7-```
It should display a different mac address as listed in the preferences.  
You need to open a new browser instance of the wifionice status page to see the new data limit.
Im on Mojave myself, so this should not be the problem.

Additionally you could try this approach:

1. disconnect from the ICE wifi manually
2. run the script
3. disable and reenable wifi
4. connect to ICE wifi

**Comment by davidswelt** [comment]
I had done all of that - except that I disabled Wifi entirely, reenabled it, and ran the script before automatically reconnecting to the wireless network.
I had open browser windows.

This time I reset the name for the DHCP lease, closed all browser windows, and disconnected from the network manually in Network Prefs.  This worked.
One of these must have done the trick.

Thanks for the help.

**Comment by Klizzy** [comment]
You're welcome!
I'll close this issue, so just open a new one if the problem occurs again
